package model;
// Generated Apr 6, 2015 11:00:35 PM by Hibernate Tools 4.3.1



import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Jugador generated by hbm2java
 */
@Entity
@Table(name="jugadores"
    ,schema="public"
)
public class Jugador  implements java.io.Serializable {


     private int codigoFide;
     private String apellidos;
     private String nombres;
     private Integer codigoNacional;
     private String pais;
     private Integer anioNacimiento;
     
    public Jugador() {
    }

	
    public Jugador(int codigoFide) {
        this.codigoFide = codigoFide;
    }
    public Jugador(int codigoFide, String apellidos, String nombres, Integer codigoNacional, String pais, Integer anioNacimiento) {
       this.codigoFide = codigoFide;
       this.apellidos = apellidos;
       this.nombres = nombres;
       this.codigoNacional = codigoNacional;
       this.pais = pais;
       this.anioNacimiento = anioNacimiento;
    }
   
    @Id 
    @Column(name="codigoFide", nullable=false)
    public int getCodigoFide() {
        return this.codigoFide;
    }
    
    public void setCodigoFide(int codigoFide) {
        this.codigoFide = codigoFide;
    }

    
    @Column(name="apellidos")
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="nombres")
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="codigoNacional")
    public Integer getCodigoNacional() {
        return this.codigoNacional;
    }
    
    public void setCodigoNacional(Integer codigoNacional) {
        this.codigoNacional = codigoNacional;
    }

    
    @Column(name="pais")
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="anioNacimiento")
    public Integer getAnioNacimiento() {
        return this.anioNacimiento;
    }
    
    public void setAnioNacimiento(Integer anioNacimiento) {
        this.anioNacimiento = anioNacimiento;
    }

}


