package model;
// Generated Apr 7, 2015 8:49:04 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Jugador generated by hbm2java
 */
@Entity
@Table(name="jugadores"
    ,schema="public"
)
public class Jugador  implements java.io.Serializable {


     private int codigofide;
     private String apellidos;
     private String nombres;
     private Integer codigonacional;
     private String pais;
     private Integer anionacimiento;
     

    public Jugador() {
    }

	
    public Jugador(int codigofide) {
        this.codigofide = codigofide;
    }
    public Jugador(int codigofide, String apellidos, String nombres, Integer codigonacional, String pais, Integer anionacimiento) {
       this.codigofide = codigofide;
       this.apellidos = apellidos;
       this.nombres = nombres;
       this.codigonacional = codigonacional;
       this.pais = pais;
       this.anionacimiento = anionacimiento;
       
    }
   
    @Id 
    @Column(name="codigofide", unique=true, nullable=false)
    public int getCodigofide() {
        return this.codigofide;
    }
    
    public void setCodigofide(int codigofide) {
        this.codigofide = codigofide;
    }

    
    @Column(name="apellidos")
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="nombres")
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="codigonacional")
    public Integer getCodigonacional() {
        return this.codigonacional;
    }
    
    public void setCodigonacional(Integer codigonacional) {
        this.codigonacional = codigonacional;
    }

    
    @Column(name="pais")
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="anionacimiento")
    public Integer getAnionacimiento() {
        return this.anionacimiento;
    }
    
    public void setAnionacimiento(Integer anionacimiento) {
        this.anionacimiento = anionacimiento;
    }

}


