package model;
// Generated Apr 3, 2015 6:07:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Jugador generated by hbm2java
 */
@Entity
@Table(name="Jugadores")
public class Jugador  implements java.io.Serializable {


     private int codigoFide;
     private String apellidos;
     private String nombres;
     private int codigoNacional;
     private String pais;
     private int anioNacimiento;

    public Jugador() {
    }

    public Jugador(int codigoFide, String apellidos, String nombres, int codigoNacional, String pais, int anioNacimiento) {
       this.codigoFide = codigoFide;
       this.apellidos = apellidos;
       this.nombres = nombres;
       this.codigoNacional = codigoNacional;
       this.pais = pais;
       this.anioNacimiento = anioNacimiento;
    }
   
    @Id 
    @Column(name="codigoFide", unique=true, nullable=false)
    public int getCodigoFide() {
        return this.codigoFide;
    }
    
    public void setCodigoFide(int codigoFide) {
        this.codigoFide = codigoFide;
    }

    
    @Column(name="apellidos", nullable=false, length=100)
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    
    @Column(name="nombres", nullable=false, length=100)
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    
    @Column(name="codigoNacional", nullable=false)
    public int getCodigoNacional() {
        return this.codigoNacional;
    }
    
    public void setCodigoNacional(int codigoNacional) {
        this.codigoNacional = codigoNacional;
    }

    
    @Column(name="pais", nullable=false, length=100)
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }

    
    @Column(name="anioNacimiento", nullable=false)
    public int getAnioNacimiento() {
        return this.anioNacimiento;
    }
    
    public void setAnioNacimiento(int anioNacimiento) {
        this.anioNacimiento = anioNacimiento;
    }




}


