package model;
// Generated Apr 3, 2015 6:07:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 *ParticipacionIdd generated by hbm2java
 */
@Embeddable
public class ParticipacionId  implements java.io.Serializable {


     private int jugadoresCodigoFide;
     private int torneosIdTorneos;

    public ParticipacionId() {
    }

    public ParticipacionId(int jugadoresCodigoFide, int torneosIdTorneos) {
       this.jugadoresCodigoFide = jugadoresCodigoFide;
       this.torneosIdTorneos = torneosIdTorneos;
    }
   


    @Column(name="Jugadores_codigoFide", nullable=false)
    public int getJugadoresCodigoFide() {
        return this.jugadoresCodigoFide;
    }
    
    public void setJugadoresCodigoFide(int jugadoresCodigoFide) {
        this.jugadoresCodigoFide = jugadoresCodigoFide;
    }


    @Column(name="Torneos_idTorneos", nullable=false)
    public int getTorneosIdTorneos() {
        return this.torneosIdTorneos;
    }
    
    public void setTorneosIdTorneos(int torneosIdTorneos) {
        this.torneosIdTorneos = torneosIdTorneos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ParticipacionId) ) return false;
		ParticipacionId castOther = (ParticipacionId ) other; 
         
		 return (this.getJugadoresCodigoFide()==castOther.getJugadoresCodigoFide())
 && (this.getTorneosIdTorneos()==castOther.getTorneosIdTorneos());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getJugadoresCodigoFide();
         result = 37 * result + this.getTorneosIdTorneos();
         return result;
   }   


}


