package model;
// Generated Apr 3, 2015 6:07:00 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Partida generated by hbm2java
 */
@Entity
@Table(name="Partidas")
public class Partida  implements java.io.Serializable {


     private Integer idPartidas;
     private int jugadoresCodigoFide;
     private int jugadoresCodigoFide1;
     private int rondasIdRondas;
     private int rondasTorneosIdTorneos;
     private String resultado;

    public Partida() {
    }

    public Partida(int jugadoresCodigoFide, int jugadoresCodigoFide1, int rondasIdRondas, int rondasTorneosIdTorneos, String resultado) {
       this.jugadoresCodigoFide = jugadoresCodigoFide;
       this.jugadoresCodigoFide1 = jugadoresCodigoFide1;
       this.rondasIdRondas = rondasIdRondas;
       this.rondasTorneosIdTorneos = rondasTorneosIdTorneos;
       this.resultado = resultado;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idPartidas", unique=true, nullable=false)
    public Integer getIdPartidas() {
        return this.idPartidas;
    }
    
    public void setIdPartidas(Integer idPartidas) {
        this.idPartidas = idPartidas;
    }

    
    @Column(name="Jugadores_codigoFide", nullable=false)
    public int getJugadoresCodigoFide() {
        return this.jugadoresCodigoFide;
    }
    
    public void setJugadoresCodigoFide(int jugadoresCodigoFide) {
        this.jugadoresCodigoFide = jugadoresCodigoFide;
    }

    
    @Column(name="Jugadores_codigoFide1", nullable=false)
    public int getJugadoresCodigoFide1() {
        return this.jugadoresCodigoFide1;
    }
    
    public void setJugadoresCodigoFide1(int jugadoresCodigoFide1) {
        this.jugadoresCodigoFide1 = jugadoresCodigoFide1;
    }

    
    @Column(name="Rondas_idRondas", nullable=false)
    public int getRondasIdRondas() {
        return this.rondasIdRondas;
    }
    
    public void setRondasIdRondas(int rondasIdRondas) {
        this.rondasIdRondas = rondasIdRondas;
    }

    
    @Column(name="Rondas_Torneos_idTorneos", nullable=false)
    public int getRondasTorneosIdTorneos() {
        return this.rondasTorneosIdTorneos;
    }
    
    public void setRondasTorneosIdTorneos(int rondasTorneosIdTorneos) {
        this.rondasTorneosIdTorneos = rondasTorneosIdTorneos;
    }

    
    @Column(name="resultado", nullable=false, length=100)
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }




}


