package model;
// Generated Apr 6, 2015 11:00:35 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Partida generated by hbm2java
 */
@Entity
@Table(name="partidas"
    ,schema="public"
)
public class Partida  implements java.io.Serializable {


     private int idPartidas;
     private Jugador jugadoresByJugadoresCodigoFide1;
     private Jugador jugadoresByJugadoresCodigoFide;
     private Ronda rondas;
     private String resultado;

    public Partida() {
    }

	
    public Partida(int idPartidas) {
        this.idPartidas = idPartidas;
    }
    public Partida(int idPartidas,Jugador jugadoresByJugadoresCodigoFide1,Jugador jugadoresByJugadoresCodigoFide, Ronda rondas, String resultado) {
       this.idPartidas = idPartidas;
       this.jugadoresByJugadoresCodigoFide1 = jugadoresByJugadoresCodigoFide1;
       this.jugadoresByJugadoresCodigoFide = jugadoresByJugadoresCodigoFide;
       this.rondas = rondas;
       this.resultado = resultado;
    }
   
     @Id 

    
    @Column(name="idPartidas", nullable=false)
    public int getIdPartidas() {
        return this.idPartidas;
    }
    
    public void setIdPartidas(int idPartidas) {
        this.idPartidas = idPartidas;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Jugadores_codigoFide1")
    public Jugador getJugadoresByJugadoresCodigoFide1() {
        return this.jugadoresByJugadoresCodigoFide1;
    }
    
    public void setJugadoresByJugadoresCodigoFide1(Jugador jugadoresByJugadoresCodigoFide1) {
        this.jugadoresByJugadoresCodigoFide1 = jugadoresByJugadoresCodigoFide1;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Jugadores_codigoFide")
    public Jugador getJugadoresByJugadoresCodigoFide() {
        return this.jugadoresByJugadoresCodigoFide;
    }
    
    public void setJugadoresByJugadoresCodigoFide(Jugador jugadoresByJugadoresCodigoFide) {
        this.jugadoresByJugadoresCodigoFide = jugadoresByJugadoresCodigoFide;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="Rondas_idRondas", referencedColumnName="idRondas"), 
        @JoinColumn(name="Rondas_Torneos_idTorneos", referencedColumnName="Torneos_idTorneos") } )
    public Ronda getRondas() {
        return this.rondas;
    }
    
    public void setRondas(Ronda rondas) {
        this.rondas = rondas;
    }

    
    @Column(name="resultado")
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }




}


