package model;
// Generated Apr 7, 2015 8:49:04 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Partida generated by hbm2java
 */
@Entity
@Table(name="partidas"
    ,schema="public"
)
public class Partida  implements java.io.Serializable {


     private int idpartidas;
     private Jugador jugadoresByJugadoresCodigofide1;
     private Jugador jugadoresByJugadoresCodigofide;
     private Ronda rondas;
     private String resultado;

    public Partida() {
    }

	
    public Partida(int idpartidas) {
        this.idpartidas = idpartidas;
    }
    public Partida(int idpartidas, Jugador jugadoresByJugadoresCodigofide1, Jugador jugadoresByJugadoresCodigofide, Ronda rondas, String resultado) {
       this.idpartidas = idpartidas;
       this.jugadoresByJugadoresCodigofide1 = jugadoresByJugadoresCodigofide1;
       this.jugadoresByJugadoresCodigofide = jugadoresByJugadoresCodigofide;
       this.rondas = rondas;
       this.resultado = resultado;
    }
   
    @Id 
    @Column(name="idpartidas", unique=true, nullable=false)
    public int getIdpartidas() {
        return this.idpartidas;
    }
    
    public void setIdpartidas(int idpartidas) {
        this.idpartidas = idpartidas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jugadores_codigofide1")
    public Jugador getJugadoresByJugadoresCodigofide1() {
        return this.jugadoresByJugadoresCodigofide1;
    }
    
    public void setJugadoresByJugadoresCodigofide1(Jugador jugadoresByJugadoresCodigofide1) {
        this.jugadoresByJugadoresCodigofide1 = jugadoresByJugadoresCodigofide1;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="jugadores_codigofide")
    public Jugador getJugadoresByJugadoresCodigofide() {
        return this.jugadoresByJugadoresCodigofide;
    }
    
    public void setJugadoresByJugadoresCodigofide(Jugador jugadoresByJugadoresCodigofide) {
        this.jugadoresByJugadoresCodigofide = jugadoresByJugadoresCodigofide;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="rondas_idrondas", referencedColumnName="idrondas"), 
        @JoinColumn(name="rondas_torneos_idtorneos", referencedColumnName="torneos_idtorneos") } )
    public Ronda getRondas() {
        return this.rondas;
    }
    
    public void setRondas(Ronda rondas) {
        this.rondas = rondas;
    }

    
    @Column(name="resultado")
    public String getResultado() {
        return this.resultado;
    }
    
    public void setResultado(String resultado) {
        this.resultado = resultado;
    }




}


