package model;
// Generated Apr 7, 2015 8:49:04 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ronda generated by hbm2java
 */
@Entity
@Table(name="rondas"
    ,schema="public"
)
public class Ronda  implements java.io.Serializable {


     private RondaId id;
     private Torneo torneos;
     private Date fecha;
     

    public Ronda() {
    }

	
    public Ronda(RondaId id, Torneo torneos) {
        this.id = id;
        this.torneos = torneos;
    }
    public Ronda(RondaId id, Torneo torneos, Date fecha) {
       this.id = id;
       this.torneos = torneos;
       this.fecha = fecha;
       
    }
   
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="idrondas", column=@Column(name="idrondas", nullable=false) ), 
        @AttributeOverride(name="torneosIdtorneos", column=@Column(name="torneos_idtorneos", nullable=false) ) } )
    public RondaId getId() {
        return this.id;
    }
    
    public void setId(RondaId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="torneos_idtorneos", nullable=false, insertable=false, updatable=false)
    public Torneo getTorneos() {
        return this.torneos;
    }
    
    public void setTorneos(Torneo torneos) {
        this.torneos = torneos;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
}


