package model;
// Generated Apr 6, 2015 11:00:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ronda generated by hbm2java
 */
@Entity
@Table(name="rondas"
    ,schema="public"
)
public class Ronda  implements java.io.Serializable {


     private RondaId id;
     private Torneo torneos;
     private Date fecha;
     private Set<Partida> partidases = new HashSet(0);

    public Ronda() {
    }

	
    public Ronda(RondaId id, Torneo torneos) {
        this.id = id;
        this.torneos = torneos;
    }
    public Ronda(RondaId id, Torneo torneos, Date fecha, Set<Partida> partidases) {
       this.id = id;
       this.torneos = torneos;
       this.fecha = fecha;
       this.partidases = partidases;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="idRondas", column=@Column(name="idRondas", nullable=false) ), 
        @AttributeOverride(name="torneosIdTorneos", column=@Column(name="Torneos_idTorneos", nullable=false) ) } )
    public RondaId getId() {
        return this.id;
    }
    
    public void setId(RondaId id) {
        this.id = id;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Torneos_idTorneos", nullable=false, insertable=false, updatable=false)
    public Torneo getTorneos() {
        return this.torneos;
    }
    
    public void setTorneos(Torneo torneos) {
        this.torneos = torneos;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", length=13)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="rondas")
    public Set getPartidases() {
        return this.partidases;
    }
    
    public void setPartidases(Set partidases) {
        this.partidases = partidases;
    }




}


