package model;
// Generated Apr 7, 2015 8:49:04 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 *RondaIdd generated by hbm2java
 */
@Embeddable
public class RondaId  implements java.io.Serializable {


     private int idrondas;
     private int torneosIdtorneos;

    public RondaId() {
    }

    public RondaId(int idrondas, int torneosIdtorneos) {
       this.idrondas = idrondas;
       this.torneosIdtorneos = torneosIdtorneos;
    }
   


    @Column(name="idrondas", nullable=false)
    public int getIdrondas() {
        return this.idrondas;
    }
    
    public void setIdrondas(int idrondas) {
        this.idrondas = idrondas;
    }


    @Column(name="torneos_idtorneos", nullable=false)
    public int getTorneosIdtorneos() {
        return this.torneosIdtorneos;
    }
    
    public void setTorneosIdtorneos(int torneosIdtorneos) {
        this.torneosIdtorneos = torneosIdtorneos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RondaId) ) return false;
		RondaId castOther = (RondaId ) other; 
         
		 return (this.getIdrondas()==castOther.getIdrondas())
 && (this.getTorneosIdtorneos()==castOther.getTorneosIdtorneos());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdrondas();
         result = 37 * result + this.getTorneosIdtorneos();
         return result;
   }   


}


