package model;
// Generated Apr 3, 2015 6:07:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ronda generated by hbm2java
 */
@Entity
@Table(name="Rondas")
public class Ronda  implements java.io.Serializable {


     private RondaId id;
     private Date fecha;

    public Ronda() {
    }

    public Ronda(RondaId id, Date fecha) {
       this.id = id;
       this.fecha = fecha;
    }
   
    @EmbeddedId
    @AttributeOverrides( {
        @AttributeOverride(name="idRondas", column=@Column(name="idRondas", nullable=false) ), 
        @AttributeOverride(name="torneosIdTorneos", column=@Column(name="Torneos_idTorneos", nullable=false) ) } )
    public RondaId getId() {
        return this.id;
    }
    
    public void setId(RondaId id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", nullable=false, length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}


