package model;
// Generated Apr 6, 2015 11:00:35 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RondaId generated by hbm2java
 */
@Embeddable
public class RondaId  implements java.io.Serializable {


     private int idRondas;
     private int torneosIdTorneos;

    public RondaId() {
    }

    public RondaId(int idRondas, int torneosIdTorneos) {
       this.idRondas = idRondas;
       this.torneosIdTorneos = torneosIdTorneos;
    }
   


    @Column(name="idRondas", nullable=false)
    public int getIdRondas() {
        return this.idRondas;
    }
    
    public void setIdRondas(int idRondas) {
        this.idRondas = idRondas;
    }


    @Column(name="Torneos_idTorneos", nullable=false)
    public int getTorneosIdTorneos() {
        return this.torneosIdTorneos;
    }
    
    public void setTorneosIdTorneos(int torneosIdTorneos) {
        this.torneosIdTorneos = torneosIdTorneos;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RondaId) ) return false;
		 RondaId castOther = ( RondaId ) other; 
         
		 return (this.getIdRondas()==castOther.getIdRondas())
 && (this.getTorneosIdTorneos()==castOther.getTorneosIdTorneos());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdRondas();
         result = 37 * result + this.getTorneosIdTorneos();
         return result;
   }   


}


