package model;
// Generated Apr 7, 2015 8:49:04 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Torneo generated by hbm2java
 */
@Entity
@Table(name="torneos"
    ,schema="public"
)
public class Torneo  implements java.io.Serializable {


     private int idtorneos;
     private String nombre;
     private String director;
     private String organizador;
     private String arbitro;
     private String lugar;
     private String federacion;
     private String tipo;
     private Date fechainicio;
     private Date fechafin;
     private Set<Jugador> jugadoreses = new HashSet<Jugador>(0);
     

    public Torneo() {
    }

	
    public Torneo(int idtorneos) {
        this.idtorneos = idtorneos;
    }
    public Torneo(int idtorneos, String nombre, String director, String organizador, String arbitro, String lugar, String federacion, String tipo, Date fechainicio, Date fechafin, Set<Jugador> jugadoreses) {
       this.idtorneos = idtorneos;
       this.nombre = nombre;
       this.director = director;
       this.organizador = organizador;
       this.arbitro = arbitro;
       this.lugar = lugar;
       this.federacion = federacion;
       this.tipo = tipo;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.jugadoreses = jugadoreses;
       
    }
   
    @Id 
    @Column(name="idtorneos", unique=true, nullable=false)
    public int getIdtorneos() {
        return this.idtorneos;
    }
    
    public void setIdtorneos(int idtorneos) {
        this.idtorneos = idtorneos;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="director")
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }

    
    @Column(name="organizador")
    public String getOrganizador() {
        return this.organizador;
    }
    
    public void setOrganizador(String organizador) {
        this.organizador = organizador;
    }

    
    @Column(name="arbitro")
    public String getArbitro() {
        return this.arbitro;
    }
    
    public void setArbitro(String arbitro) {
        this.arbitro = arbitro;
    }

    
    @Column(name="lugar")
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    
    @Column(name="federacion")
    public String getFederacion() {
        return this.federacion;
    }
    
    public void setFederacion(String federacion) {
        this.federacion = federacion;
    }

    
    @Column(name="tipo")
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechainicio", length=13)
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechafin", length=13)
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="participaciones", schema="public", joinColumns = { 
        @JoinColumn(name="torneos_idtorneos", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="jugadores_codigofide", nullable=false, updatable=false) })
    public Set<Jugador> getJugadoreses() {
        return this.jugadoreses;
    }
    
    public void setJugadoreses(Set<Jugador> jugadoreses) {
        this.jugadoreses = jugadoreses;
    }

}


