package model;
// Generated Apr 6, 2015 11:00:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Torneo generated by hbm2java
 */
@Entity
@Table(name="torneos"
    ,schema="public"
)
public class Torneo  implements java.io.Serializable {


     private int idTorneos;
     private String nombre;
     private String director;
     private String organizador;
     private String arbitro;
     private String lugar;
     private String federacion;
     private String tipo;
     private Date fechaInicio;
     private Date fechaFin;
     private Set<Jugador> jugadoreses = new HashSet(0);
     private Set<Ronda> rondases = new HashSet(0);

    public Torneo() {
    }

	
    public Torneo(int idTorneos) {
        this.idTorneos = idTorneos;
    }
    public Torneo(int idTorneos, String nombre, String director, String organizador, String arbitro, String lugar, String federacion, String tipo, Date fechaInicio, Date fechaFin, Set<Jugador> jugadoreses, Set<Ronda> rondases) {
       this.idTorneos = idTorneos;
       this.nombre = nombre;
       this.director = director;
       this.organizador = organizador;
       this.arbitro = arbitro;
       this.lugar = lugar;
       this.federacion = federacion;
       this.tipo = tipo;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.jugadoreses = jugadoreses;
       this.rondases = rondases;
    }
   
    @Id 
    @Column(name="idTorneos", nullable=false)
    public int getIdTorneos() {
        return this.idTorneos;
    }
    
    public void setIdTorneos(int idTorneos) {
        this.idTorneos = idTorneos;
    }

    
    @Column(name="nombre")
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="director")
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }

    
    @Column(name="organizador")
    public String getOrganizador() {
        return this.organizador;
    }
    
    public void setOrganizador(String organizador) {
        this.organizador = organizador;
    }

    
    @Column(name="arbitro")
    public String getArbitro() {
        return this.arbitro;
    }
    
    public void setArbitro(String arbitro) {
        this.arbitro = arbitro;
    }

    
    @Column(name="lugar")
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    
    @Column(name="federacion")
    public String getFederacion() {
        return this.federacion;
    }
    
    public void setFederacion(String federacion) {
        this.federacion = federacion;
    }

    
    @Column(name="tipo")
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaInicio", length=13)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaFin", length=13)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="participaciones", schema="public", joinColumns = { 
        @JoinColumn(name="Torneos_idTorneos", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Jugadores_codigoFide", nullable=false, updatable=false) })
    public Set getJugadoreses() {
        return this.jugadoreses;
    }
    
    public void setJugadoreses(Set jugadoreses) {
        this.jugadoreses = jugadoreses;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="torneos")
    public Set getRondases() {
        return this.rondases;
    }
    
    public void setRondases(Set rondases) {
        this.rondases = rondases;
    }




}


