package model;
// Generated Apr 3, 2015 6:07:00 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Torneo generated by hbm2java
 */
@Entity
@Table(name="Torneos")
public class Torneo  implements java.io.Serializable {


    private Integer idTorneos;
    private String nombre;
    private String director;
    private String organizador;
    private String arbitro;
    private String lugar;
    private String federacion;
    private String tipo;
    private Date fechaInicio;
    private Date fechaFin;

    public Torneo() {
    }

    public Torneo(String nombre, String director, String organizador, String arbitro, String lugar, String federacion, String tipo, Date fechaInicio, Date fechaFin) {
       this.nombre = nombre;
       this.director = director;
       this.organizador = organizador;
       this.arbitro = arbitro;
       this.lugar = lugar;
       this.federacion = federacion;
       this.tipo = tipo;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="idTorneos", unique=true, nullable=false)
    public Integer getIdTorneos() {
        return this.idTorneos;
    }
    
    public void setIdTorneos(Integer idTorneos) {
        this.idTorneos = idTorneos;
    }

    
    @Column(name="nombre", nullable=false, length=100)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="director", nullable=false, length=100)
    public String getDirector() {
        return this.director;
    }
    
    public void setDirector(String director) {
        this.director = director;
    }

    
    @Column(name="organizador", nullable=false, length=100)
    public String getOrganizador() {
        return this.organizador;
    }
    
    public void setOrganizador(String organizador) {
        this.organizador = organizador;
    }

    
    @Column(name="arbitro", nullable=false, length=100)
    public String getArbitro() {
        return this.arbitro;
    }
    
    public void setArbitro(String arbitro) {
        this.arbitro = arbitro;
    }

    
    @Column(name="lugar", nullable=false, length=100)
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }

    
    @Column(name="federacion", nullable=false, length=100)
    public String getFederacion() {
        return this.federacion;
    }
    
    public void setFederacion(String federacion) {
        this.federacion = federacion;
    }

    
    @Column(name="tipo", nullable=false, length=100)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaInicio", nullable=false, length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fechaFin", nullable=false, length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


